### ISSUE TITLE
UnifyValues and UnificationTable

### ISSUE THREAD

**Issue by WaDelma** [rust-lang-nursery/ena#4]
I am trying to implement algorithm w based on the wikipedia description.
As far as I understand I should be unifying monotypes, so I created key type that implements `UnifyKey` with my monotype enum as associated value.

Then I tried to implement `UnifyValue` for the monotype. This seems to be impossible, as for the type constructors I need to recursively unify each parameter, which I can't do as `unify_values` doesn't take `UnificationTable` as parameter.

Am I missing something or is this deficiency in the library?

**Comment by nikomatsakis** [comment]
@WaDelma you may be intersted in e.g. [chalk's  unification code](https://github.com/rust-lang-nursery/chalk/blob/master/src/solve/infer/unify.rs), which implements an extension of algorithm W. The answer is that you want this recursion to be taking place *outside* of the unification table. 

In other words, you first check if the LHS or RHS has been unified. If both have not, *then* you unify.
